// Generated by scripts/generate-coach-knowledge.mjs. Edit apps/worker/knowledge/*.md instead.
export interface KnowledgeChunk { id: string; documentId: string; title: string; section: string; content: string }
export const COACH_KNOWLEDGE: readonly KnowledgeChunk[] = [
  {
    "id": "common_mistakes:trying-to-progress-too-quickly:1",
    "documentId": "common_mistakes",
    "title": "Common Exercise and Training Mistakes",
    "section": "Trying to progress too quickly",
    "content": "Problem:\nIncreasing repetitions or difficulty too quickly can make recovery harder and technique worse.\n\nBetter approach:\nIncrease difficulty gradually."
  },
  {
    "id": "common_mistakes:chasing-repetitions-instead-of-form:1",
    "documentId": "common_mistakes",
    "title": "Common Exercise and Training Mistakes",
    "section": "Chasing repetitions instead of form",
    "content": "Problem:\nDoing more repetitions with poor technique does not necessarily mean better performance.\n\nBetter approach:\nPrioritize controlled repetitions."
  },
  {
    "id": "common_mistakes:training-to-exhaustion-every-time:1",
    "documentId": "common_mistakes",
    "title": "Common Exercise and Training Mistakes",
    "section": "Training to exhaustion every time",
    "content": "Problem:\nEvery workout does not need to be maximal.\n\nBetter approach:\nUse challenging but manageable training."
  },
  {
    "id": "common_mistakes:ignoring-recovery:1",
    "documentId": "common_mistakes",
    "title": "Common Exercise and Training Mistakes",
    "section": "Ignoring recovery",
    "content": "Problem:\nTraining without enough recovery can reduce performance.\n\nBetter approach:\nAllow enough rest, food, hydration, and sleep."
  },
  {
    "id": "common_mistakes:doing-only-cardio-to-become-lean:1",
    "documentId": "common_mistakes",
    "title": "Common Exercise and Training Mistakes",
    "section": "Doing only cardio to become lean",
    "content": "Problem:\nCardio can help with energy expenditure and fitness, but removing strength training can make muscle retention harder.\n\nBetter approach:\nCombine resistance training with appropriate cardio and nutrition."
  },
  {
    "id": "common_mistakes:eating-far-too-little:1",
    "documentId": "common_mistakes",
    "title": "Common Exercise and Training Mistakes",
    "section": "Eating far too little",
    "content": "Problem:\nVery aggressive dieting can cause tiredness and may make muscle and strength retention harder.\n\nBetter approach:\nUse a moderate and sustainable approach."
  },
  {
    "id": "common_mistakes:avoiding-carbohydrates-completely:1",
    "documentId": "common_mistakes",
    "title": "Common Exercise and Training Mistakes",
    "section": "Avoiding carbohydrates completely",
    "content": "Problem:\nCarbohydrates are a useful source of energy, especially for demanding exercise.\n\nBetter approach:\nChoose an appropriate amount based on the person's goal and activity."
  },
  {
    "id": "common_mistakes:copying-another-person-s-diet:1",
    "documentId": "common_mistakes",
    "title": "Common Exercise and Training Mistakes",
    "section": "Copying another person's diet",
    "content": "Problem:\nFood requirements differ between people.\n\nBetter approach:\nAdapt food choices to the person's needs, preferences, activity, and goal."
  },
  {
    "id": "common_mistakes:poor-warm-up:1",
    "documentId": "common_mistakes",
    "title": "Common Exercise and Training Mistakes",
    "section": "Poor warm-up",
    "content": "Problem:\nStarting intense exercise immediately can feel uncomfortable.\n\nBetter approach:\nBegin with light movement and gradually increase intensity."
  },
  {
    "id": "common_mistakes:ignoring-pain:1",
    "documentId": "common_mistakes",
    "title": "Common Exercise and Training Mistakes",
    "section": "Ignoring pain",
    "content": "Normal effort and mild temporary fatigue are different from sharp, severe, or unusual pain.\n\nIf an exercise causes significant pain, stop the exercise and seek appropriate professional advice."
  },
  {
    "id": "common_mistakes:poor-exercise-selection:1",
    "documentId": "common_mistakes",
    "title": "Common Exercise and Training Mistakes",
    "section": "Poor exercise selection",
    "content": "A person does not need every exercise.\n\nChoose movements that:\n\nMatch the goal\nCan be performed safely\nCan be progressed\nFit available equipment\nThe person can perform consistently"
  },
  {
    "id": "common_mistakes:comparing-performance-with-others:1",
    "documentId": "common_mistakes",
    "title": "Common Exercise and Training Mistakes",
    "section": "Comparing performance with others",
    "content": "People have different:\n\nStrength\nBody structure\nExperience\nRecovery\nFitness levels\n\nCompare improvements with your own previous performance."
  },
  {
    "id": "exercises:what-exercise-does:1",
    "documentId": "exercises",
    "title": "Exercise Knowledge",
    "section": "What exercise does",
    "content": "Exercise helps improve strength, muscle, fitness, stamina, movement quality, and overall physical performance.\n\nDifferent exercises have different purposes. A good training plan normally combines several types of movement instead of doing only one exercise.\n\nThe main types of exercise are:\n\nStrength exercises\nMuscle-building exercises\nCardio and running\nCore exercises\nMobility exercises\nBalance and coordination exercises\nRecovery activities"
  },
  {
    "id": "exercises:chest:1",
    "documentId": "exercises",
    "title": "Exercise Knowledge",
    "section": "Chest",
    "content": "Main movements:\n\nPush-ups\nBench press\nDumbbell press\nIncline press\nChest fly\n\nPush-ups are a useful bodyweight option because they train the chest while also involving the shoulders, triceps, and core."
  },
  {
    "id": "exercises:back:1",
    "documentId": "exercises",
    "title": "Exercise Knowledge",
    "section": "Back",
    "content": "Main movements:\n\nPull-ups\nAssisted pull-ups\nRows\nLat pulldowns\nDumbbell rows\n\nBack exercises help improve pulling strength and upper-body stability."
  },
  {
    "id": "exercises:shoulders:1",
    "documentId": "exercises",
    "title": "Exercise Knowledge",
    "section": "Shoulders",
    "content": "Main movements:\n\nOverhead press\nDumbbell shoulder press\nLateral raises\nRear-delt raises"
  },
  {
    "id": "exercises:arms:1",
    "documentId": "exercises",
    "title": "Exercise Knowledge",
    "section": "Arms",
    "content": "Biceps:\n\nCurls\nHammer curls\nChin-ups\n\nTriceps:\n\nPush-ups\nClose-grip push-ups\nDips\nTriceps extensions"
  },
  {
    "id": "exercises:legs:1",
    "documentId": "exercises",
    "title": "Exercise Knowledge",
    "section": "Legs",
    "content": "Quadriceps:\n\nSquats\nSplit squats\nLunges\nStep-ups\n\nGlutes:\n\nSquats\nHip thrusts\nGlute bridges\nLunges\nSplit squats\n\nHamstrings:\n\nRomanian deadlifts\nHamstring curls\nHip hinges\n\nCalves:\n\nCalf raises\nSingle-leg calf raises"
  },
  {
    "id": "exercises:core:1",
    "documentId": "exercises",
    "title": "Exercise Knowledge",
    "section": "Core",
    "content": "The core includes the muscles around the abdomen, sides, hips, and lower back.\n\nUseful exercises:\n\nPlank\nSide plank\nDead bug\nBird dog\nLeg raises\nControlled mountain climbers"
  },
  {
    "id": "exercises:compound-exercises:1",
    "documentId": "exercises",
    "title": "Exercise Knowledge",
    "section": "Compound exercises",
    "content": "Compound exercises use several joints and muscle groups.\n\nExamples:\n\nSquat\nPush-up\nPull-up\nRow\nDeadlift\nLunge\nOverhead press\n\nThey are useful when a person wants to train many muscles efficiently."
  },
  {
    "id": "exercises:isolation-exercises:1",
    "documentId": "exercises",
    "title": "Exercise Knowledge",
    "section": "Isolation exercises",
    "content": "Isolation exercises focus more strongly on one muscle or movement.\n\nExamples:\n\nBiceps curl\nTriceps extension\nLateral raise\nCalf raise\nLeg curl\n\nIsolation exercises can be added after larger movements."
  },
  {
    "id": "exercises:exercise-selection:1",
    "documentId": "exercises",
    "title": "Exercise Knowledge",
    "section": "Exercise selection",
    "content": "Choose exercises based on the person's:\n\nGoal\nExperience\nAvailable equipment\nCurrent strength\nMobility\nFitness level\nComfort with the movement\n\nA beginner does not need advanced exercises.\n\nA simple program can use:\n\nSquat\nPush-up\nRow or pull movement\nHip-hinge movement\nCore exercise\nWalking or running"
  },
  {
    "id": "exercises:bodyweight-training:1",
    "documentId": "exercises",
    "title": "Exercise Knowledge",
    "section": "Bodyweight training",
    "content": "Bodyweight exercises are useful because they require little or no equipment.\n\nExamples:\n\nSquats\nPush-ups\nLunges\nPlanks\nGlute bridges\nStep-ups\nMountain climbers\n\nExercises can be made easier or harder by changing:\n\nRange of motion\nRepetitions\nTempo\nRest time\nBody position\nExercise variation"
  },
  {
    "id": "exercises:exercise-quality:1",
    "documentId": "exercises",
    "title": "Exercise Knowledge",
    "section": "Exercise quality",
    "content": "Good exercise is not only about doing more repetitions.\n\nImportant factors include:\n\nGood technique\nControlled movement\nAppropriate range of motion\nConsistency\nGradual progression\nRecovery\n\nIf technique becomes poor because of fatigue, the person should reduce difficulty or rest."
  },
  {
    "id": "foods:protein-rich-foods-vegetarian:1",
    "documentId": "foods",
    "title": "Food Guide for Fitness Goals",
    "section": "Protein-rich foods / Vegetarian",
    "content": "Paneer\nTofu\nSoy chunks\nTempeh\nMilk\nYogurt\nGreek yogurt\nLentils\nDal\nChickpeas\nKidney beans\nBlack beans\nPeas\nEdamame\nEggs, if included in the person's diet"
  },
  {
    "id": "foods:protein-rich-foods-non-vegetarian:1",
    "documentId": "foods",
    "title": "Food Guide for Fitness Goals",
    "section": "Protein-rich foods / Non-vegetarian",
    "content": "Chicken\nFish\nEggs\nLean meat"
  },
  {
    "id": "foods:carbohydrate-rich-foods:1",
    "documentId": "foods",
    "title": "Food Guide for Fitness Goals",
    "section": "Carbohydrate-rich foods",
    "content": "Useful options:\n\nRice\nRoti\nOats\nPotatoes\nSweet potatoes\nWhole-grain bread\nFruits\nCorn\nQuinoa\nDal\nBeans"
  },
  {
    "id": "foods:healthy-fat-sources:1",
    "documentId": "foods",
    "title": "Food Guide for Fitness Goals",
    "section": "Healthy fat sources",
    "content": "Nuts\nSeeds\nPeanut butter\nAvocado\nOlive oil\nEggs\nDairy"
  },
  {
    "id": "foods:foods-useful-for-muscle-gain:1",
    "documentId": "foods",
    "title": "Food Guide for Fitness Goals",
    "section": "Foods useful for muscle gain",
    "content": "Choose combinations such as:\n\nRice + dal + paneer\nRoti + paneer + vegetables\nRice + chicken + vegetables\nOats + milk + fruit\nYogurt + fruit + nuts\nTofu + rice + vegetables\nEggs + toast + fruit\n\nThe goal is to make meals sufficiently nutritious and provide enough total food."
  },
  {
    "id": "foods:foods-useful-for-getting-lean:1",
    "documentId": "foods",
    "title": "Food Guide for Fitness Goals",
    "section": "Foods useful for getting lean",
    "content": "Foods with high protein and/or high fiber can make it easier to stay full.\n\nExamples:\n\nEggs\nTofu\nPaneer in appropriate portions\nYogurt\nDal\nChickpeas\nBeans\nVegetables\nFruits\nOats\nPotatoes\nWhole grains\n\nPortion size still matters.\n\nA healthy food can contribute to excess calories if eaten in very large amounts."
  },
  {
    "id": "foods:foods-useful-before-exercise:1",
    "documentId": "foods",
    "title": "Food Guide for Fitness Goals",
    "section": "Foods useful before exercise",
    "content": "Examples:\n\nBanana\nOats\nToast\nRice\nFruit\nYogurt\nLight meal with carbohydrates and protein"
  },
  {
    "id": "foods:foods-useful-after-exercise:1",
    "documentId": "foods",
    "title": "Food Guide for Fitness Goals",
    "section": "Foods useful after exercise",
    "content": "Examples:\n\nRice + dal\nRoti + paneer\nChicken + rice\nEggs + toast\nYogurt + oats + fruit\nTofu + rice"
  },
  {
    "id": "foods:easy-meal-structure:1",
    "documentId": "foods",
    "title": "Food Guide for Fitness Goals",
    "section": "Easy meal structure",
    "content": "Breakfast:\nProtein + carbohydrate + fruit.\n\nLunch:\nProtein + carbohydrate + vegetables.\n\nSnack:\nFruit + yogurt, milk, nuts, or another suitable food.\n\nDinner:\nProtein + carbohydrate + vegetables.\n\nThis is only a template and can be adjusted to the person's preferences."
  },
  {
    "id": "foods:food-first-habits:1",
    "documentId": "foods",
    "title": "Food Guide for Fitness Goals",
    "section": "Food-first habits",
    "content": "Build sustainable habits around normal foods, hydration, exercise, and recovery. Supplements are not required to follow the food examples in this guide."
  },
  {
    "id": "getting_lean:what-getting-lean-means:1",
    "documentId": "getting_lean",
    "title": "Getting Lean While Maintaining Muscle and Strength",
    "section": "What getting lean means",
    "content": "Getting lean usually means reducing body fat while trying to keep as much muscle and strength as possible.\n\nThe goal should not simply be losing as much body weight as possible."
  },
  {
    "id": "getting_lean:main-principles:1",
    "documentId": "getting_lean",
    "title": "Getting Lean While Maintaining Muscle and Strength",
    "section": "Main principles",
    "content": "To preserve muscle while losing fat:\n\nUse a moderate calorie deficit\nEat enough protein\nContinue resistance training\nKeep training performance as high as reasonably possible\nGet enough sleep\nAvoid extreme dieting"
  },
  {
    "id": "getting_lean:calorie-deficit:1",
    "documentId": "getting_lean",
    "title": "Getting Lean While Maintaining Muscle and Strength",
    "section": "Calorie deficit",
    "content": "A calorie deficit means the body uses more energy than it receives from food over time.\n\nA moderate deficit is generally more sustainable than a very aggressive deficit.\n\nVery fast weight loss can increase the risk of losing muscle and feeling tired."
  },
  {
    "id": "getting_lean:protein-during-fat-loss:1",
    "documentId": "getting_lean",
    "title": "Getting Lean While Maintaining Muscle and Strength",
    "section": "Protein during fat loss",
    "content": "Protein becomes especially important when eating fewer calories.\n\nGood options include:\n\nEggs\nMilk\nYogurt\nPaneer\nTofu\nSoy\nLentils\nChickpeas\nBeans\nFish\nChicken\nLean meat"
  },
  {
    "id": "getting_lean:strength-training-during-fat-loss:1",
    "documentId": "getting_lean",
    "title": "Getting Lean While Maintaining Muscle and Strength",
    "section": "Strength training during fat loss",
    "content": "Do not replace all strength training with cardio.\n\nResistance training tells the body that muscle is still needed.\n\nThe person should try to maintain strength and good training quality.\n\nSome reduction in performance can happen during a calorie deficit, especially when the deficit is large or recovery is poor."
  },
  {
    "id": "getting_lean:cardio-during-fat-loss:1",
    "documentId": "getting_lean",
    "title": "Getting Lean While Maintaining Muscle and Strength",
    "section": "Cardio during fat loss",
    "content": "Useful cardio includes:\n\nWalking\nJogging\nRunning\nCycling\nSwimming\nSports\n\nThe best option is one the person can perform consistently."
  },
  {
    "id": "getting_lean:what-not-to-do:1",
    "documentId": "getting_lean",
    "title": "Getting Lean While Maintaining Muscle and Strength",
    "section": "What not to do",
    "content": "Avoid:\n\nExtreme fasting solely for faster weight loss\nExtremely low-calorie diets\nRemoving all carbohydrates without a reason\nDoing excessive cardio while eating very little\nTrying to lose weight as quickly as possible\nIgnoring strength training"
  },
  {
    "id": "getting_lean:measuring-progress:1",
    "documentId": "getting_lean",
    "title": "Getting Lean While Maintaining Muscle and Strength",
    "section": "Measuring progress",
    "content": "Body weight is only one measurement.\n\nOther useful indicators:\n\nWaist measurement\nStrength\nExercise performance\nEnergy levels\nHow clothes fit\nProgress photos when appropriate\n\nDaily weight can change because of water, food, sodium, and other factors.\n\nLook at trends rather than one day's number."
  },
  {
    "id": "getting_lean:main-nutrients:1",
    "documentId": "getting_lean",
    "title": "Getting Lean While Maintaining Muscle and Strength",
    "section": "Main nutrients",
    "content": "The three main macronutrients are:"
  },
  {
    "id": "getting_lean:protein:1",
    "documentId": "getting_lean",
    "title": "Getting Lean While Maintaining Muscle and Strength",
    "section": "Protein",
    "content": "Protein supports:\n\nMuscle repair\nMuscle growth\nRecovery\nSatiety\n\nSources:\n\nEggs\nMilk\nYogurt\nPaneer\nTofu\nSoy\nLentils\nBeans\nChickpeas\nFish\nChicken\nLean meat"
  },
  {
    "id": "getting_lean:carbohydrates:1",
    "documentId": "getting_lean",
    "title": "Getting Lean While Maintaining Muscle and Strength",
    "section": "Carbohydrates",
    "content": "Carbohydrates provide an important source of energy.\n\nSources:\n\nRice\nRoti\nOats\nPotatoes\nSweet potatoes\nFruits\nWhole grains\nBeans\nLentils\n\nCarbohydrates can be especially useful before demanding exercise."
  },
  {
    "id": "getting_lean:fats:1",
    "documentId": "getting_lean",
    "title": "Getting Lean While Maintaining Muscle and Strength",
    "section": "Fats",
    "content": "Dietary fats are important for normal body functions.\n\nSources:\n\nNuts\nSeeds\nPeanut butter\nAvocado\nOlive oil\nDairy\nEggs"
  },
  {
    "id": "getting_lean:fiber:1",
    "documentId": "getting_lean",
    "title": "Getting Lean While Maintaining Muscle and Strength",
    "section": "Fiber",
    "content": "Fiber supports digestion and can help a person feel full.\n\nSources:\n\nVegetables\nFruits\nWhole grains\nBeans\nLentils\nChickpeas\nSeeds"
  },
  {
    "id": "getting_lean:balanced-meals:1",
    "documentId": "getting_lean",
    "title": "Getting Lean While Maintaining Muscle and Strength",
    "section": "Balanced meals",
    "content": "A simple meal can contain:\n\nA protein source\nA carbohydrate source\nVegetables or fruit\nA source of healthy fat when appropriate\n\nExample:\nRice + dal + vegetables + yogurt.\n\nAnother example:\nRoti + paneer/tofu + vegetables + fruit."
  },
  {
    "id": "getting_lean:pre-workout-food:1",
    "documentId": "getting_lean",
    "title": "Getting Lean While Maintaining Muscle and Strength",
    "section": "Pre-workout food",
    "content": "Before exercise, a person can choose foods that are easy to digest.\n\nExamples:\n\nBanana\nOats\nToast\nRice\nYogurt\nFruit\nA simple meal containing carbohydrates and protein\n\nAvoid very heavy meals immediately before intense exercise if they cause discomfort."
  },
  {
    "id": "getting_lean:post-workout-food:1",
    "documentId": "getting_lean",
    "title": "Getting Lean While Maintaining Muscle and Strength",
    "section": "Post-workout food",
    "content": "A normal balanced meal after training is enough for most people.\n\nIt can contain:\n\nProtein\n\nCarbohydrates\n\nVegetables or fruit\nFluids"
  },
  {
    "id": "getting_lean:hydration:1",
    "documentId": "getting_lean",
    "title": "Getting Lean While Maintaining Muscle and Strength",
    "section": "Hydration",
    "content": "Drink water regularly throughout the day.\n\nMore fluid may be needed when:\n\nIt is hot\nExercise is long\nThe person sweats heavily\nThe person is doing intense exercise\n\nDo not wait until severe thirst appears before drinking."
  },
  {
    "id": "getting_lean:diet-for-strength:1",
    "documentId": "getting_lean",
    "title": "Getting Lean While Maintaining Muscle and Strength",
    "section": "Diet for strength",
    "content": "Prioritize:\n\nEnough total food\nAdequate protein\nEnough carbohydrates for training\nFruits and vegetables\nHealthy fats\nGood hydration"
  },
  {
    "id": "getting_lean:diet-for-muscle-gain:1",
    "documentId": "getting_lean",
    "title": "Getting Lean While Maintaining Muscle and Strength",
    "section": "Diet for muscle gain",
    "content": "Prioritize:\n\nEnough calories\nAdequate protein\nCarbohydrates for training\nRegular meals\nNutrient-rich foods\n\nA small calorie surplus can be useful."
  },
  {
    "id": "getting_lean:diet-for-getting-lean:1",
    "documentId": "getting_lean",
    "title": "Getting Lean While Maintaining Muscle and Strength",
    "section": "Diet for getting lean",
    "content": "Prioritize:\n\nA moderate calorie deficit\nHigh-quality protein\nPlenty of vegetables and fruit\nHigh-fiber foods\nReasonable carbohydrate portions\nHealthy fats in appropriate portions\n\nThe diet should still provide enough energy to train."
  },
  {
    "id": "getting_lean:diet-quality:1",
    "documentId": "getting_lean",
    "title": "Getting Lean While Maintaining Muscle and Strength",
    "section": "Diet quality",
    "content": "Fitness does not require eating perfectly.\n\nA sustainable diet can include foods a person enjoys.\n\nConsistency matters more than perfection."
  },
  {
    "id": "getting_lean:individual-differences:1",
    "documentId": "getting_lean",
    "title": "Getting Lean While Maintaining Muscle and Strength",
    "section": "Individual differences",
    "content": "Food needs depend on:\n\nAge\nBody size\nActivity level\nTraining volume\nGoal\nFood preferences\nDietary restrictions\n\nFood needs vary; one diet does not work for everyone. This guide is general fitness information, not medical nutrition advice."
  },
  {
    "id": "muscle_gain:what-muscle-gain-means:1",
    "documentId": "muscle_gain",
    "title": "Muscle Gain",
    "section": "What muscle gain means",
    "content": "Muscle gain means increasing muscle size over time.\n\nMuscle growth is supported by:\n\nResistance training\n\nEnough food\nEnough protein\nRecovery\n\nSleep\n\nConsistency"
  },
  {
    "id": "muscle_gain:resistance-training:1",
    "documentId": "muscle_gain",
    "title": "Muscle Gain",
    "section": "Resistance training",
    "content": "Muscles need a reason to adapt.\n\nUseful training includes:\n\nSquats\nLunges\nPush-ups\nPresses\nRows\nPull-ups\nHip hinges\nCurls\nTriceps exercises\nCalf exercises"
  },
  {
    "id": "muscle_gain:repetitions:1",
    "documentId": "muscle_gain",
    "title": "Muscle Gain",
    "section": "Repetitions",
    "content": "Muscle growth can happen across a relatively wide repetition range when the exercise is challenging enough.\n\nA practical approach is to use moderate repetitions and gradually increase difficulty."
  },
  {
    "id": "muscle_gain:sets:1",
    "documentId": "muscle_gain",
    "title": "Muscle Gain",
    "section": "Sets",
    "content": "More training volume can support growth, but more is not always better.\n\nIf a person constantly feels exhausted or their performance is getting worse, training volume may be too high."
  },
  {
    "id": "muscle_gain:training-close-to-failure:1",
    "documentId": "muscle_gain",
    "title": "Muscle Gain",
    "section": "Training close to failure",
    "content": "A set can be challenging without every set being an all-out effort.\n\nMost training should allow the person to maintain good technique.\n\nStopping a set when technique is breaking down is better than forcing poor repetitions."
  },
  {
    "id": "muscle_gain:protein:1",
    "documentId": "muscle_gain",
    "title": "Muscle Gain",
    "section": "Protein",
    "content": "Protein provides amino acids used by the body for muscle repair and growth.\n\nUseful protein foods include:\n\nEggs\nMilk\nYogurt\nPaneer\nTofu\nSoy\nLentils\nBeans\nChickpeas\nFish\nChicken\nLean meat\n\nFor vegetarian diets, combining different protein-rich foods throughout the day can help."
  },
  {
    "id": "muscle_gain:calories:1",
    "documentId": "muscle_gain",
    "title": "Muscle Gain",
    "section": "Calories",
    "content": "Muscle gain can be easier when the person has enough energy available.\n\nA small calorie surplus may support muscle gain, but very large surpluses are not necessary.\n\nRapid weight gain can increase unnecessary fat gain."
  },
  {
    "id": "muscle_gain:sleep:1",
    "documentId": "muscle_gain",
    "title": "Muscle Gain",
    "section": "Sleep",
    "content": "Sleep supports recovery and physical performance.\n\nA consistent sleep schedule is useful."
  },
  {
    "id": "muscle_gain:muscle-gain-and-cardio:1",
    "documentId": "muscle_gain",
    "title": "Muscle Gain",
    "section": "Muscle gain and cardio",
    "content": "Cardio does not automatically prevent muscle growth.\n\nA person can combine strength training and cardio.\n\nHowever, very large amounts of intense cardio combined with insufficient food and recovery can make muscle gain harder."
  },
  {
    "id": "progression:gradual-training-progression:1",
    "documentId": "progression",
    "title": "Training and Character Progression",
    "section": "Gradual training progression",
    "content": "Progression means improving what your body can do over time. It can mean more controlled repetitions, more resistance, a harder variation, a larger comfortable range of motion, or more running time. It does not always mean adding weight.\n\nLearn the movement first. Increase one training demand at a time only when you can perform the current level consistently with good technique. Increasing volume, intensity, frequency, and speed together makes recovery harder."
  },
  {
    "id": "progression:push-up-progression:1",
    "documentId": "progression",
    "title": "Training and Character Progression",
    "section": "Push-up progression",
    "content": "Possible steps are wall push-ups, incline push-ups, knee push-ups when appropriate, standard push-ups, close-grip push-ups, and decline push-ups. Choose a variation you can control. The exact sequence depends on your ability."
  },
  {
    "id": "progression:squat-progression:1",
    "documentId": "progression",
    "title": "Training and Character Progression",
    "section": "Squat progression",
    "content": "Possible steps are bodyweight squats, controlled squats, pause squats, split squats, Bulgarian split squats, and loaded squats when appropriate. Comfortable depth, stable feet, and controlled movement come before more repetitions."
  },
  {
    "id": "progression:running-progression:1",
    "documentId": "progression",
    "title": "Training and Character Progression",
    "section": "Running progression",
    "content": "Start with walking, then walk/jog intervals, longer jogging periods, continuous running, and eventually longer or faster runs. Increase only one major demand at a time. VYRA's current camera workouts do not record running distance or pace."
  },
  {
    "id": "progression:four-character-stages-and-elite-requirements:1",
    "documentId": "progression",
    "title": "Training and Character Progression",
    "section": "Four character stages and Elite requirements",
    "content": "VYRA's earned journey finishes at Elite: Starter, Developing, Strong, Elite. New players begin at Starter. Stage upgrades require both workout progress and progress toward the chosen target weight, confirmed by a later body check-in.\n\n- Developing: 100 XP, 1 active day, and at least 25% of the way from starting weight to target weight.\n- Strong: 1,000 XP, 5 active days, and at least 60% toward target weight.\n- Elite: 3,000 XP, 14 active days, and reaching the chosen target weight.\n\nFor a maintenance goal, a later check-in within 2% of the chosen target weight satisfies the weight requirement. A weight report alone never grants XP or active days. Legendary is not an additional earned goal in this journey."
  },
  {
    "id": "progression:body-check-ins-and-target-weight:1",
    "documentId": "progression",
    "title": "Training and Character Progression",
    "section": "Body check-ins and target weight",
    "content": "Choose a goal, starting build, height, current weight, target weight, and character during setup. Your starting measurements stay fixed as the baseline. Add height and weight reports from the next calendar day onward; days follow Asia/Kolkata time. A new report on the same day updates that day's report. Weekly check-ins are a useful rhythm; daily reporting is not required.\n\nCharacter stages stay earned through normal weight fluctuations or missed reports. Self-reported weight is a goal metric, not a measurement of muscle gain or overall fitness. Training quality, performance, energy, recovery, and how you feel also matter."
  },
  {
    "id": "progression:workout-xp-and-active-days:1",
    "documentId": "progression",
    "title": "Training and Character Progression",
    "section": "Workout XP and active days",
    "content": "A completed workout needs at least 10 valid repetitions to qualify. The first three qualifying workouts each day earn XP; further valid workouts can still add repetitions and wins for cosmetic unlocks. Active days count distinct days with a qualifying workout, not the number of workouts completed on one day."
  },
  {
    "id": "progression:workout-and-body-progress-together:1",
    "documentId": "progression",
    "title": "Training and Character Progression",
    "section": "Workout and body progress together",
    "content": "If your character has not evolved, check all requirements: XP, distinct active days, a later body check-in, and progress toward your chosen target. For example, with a gain goal from 55 kg to 65 kg, 25% progress is 57.5 kg. Developing still also needs 100 XP and 1 active day. Do not rush weight changes to unlock a character stage."
  },
  {
    "id": "progression:tracking-useful-training-progress:1",
    "documentId": "progression",
    "title": "Training and Character Progression",
    "section": "Tracking useful training progress",
    "content": "Record repetitions, manageable exercise variations, comfortable range of motion, and how well you recover. A training plateau may call for better sleep, easier sessions, technique practice, or more consistent training, rather than simply more volume. Previewing a stage or choosing a different character does not award progress."
  },
  {
    "id": "pushup:muscles-worked-by-push-ups:1",
    "documentId": "pushup",
    "title": "Push-up Improvement",
    "section": "Muscles worked by push-ups",
    "content": "Push-ups mainly train the chest, shoulders, and triceps while the core helps maintain body position."
  },
  {
    "id": "pushup:good-push-up-form-and-setup:1",
    "documentId": "pushup",
    "title": "Push-up Improvement",
    "section": "Good push-up form and setup",
    "content": "Place hands on a stable surface.\nKeep the body in a controlled straight line.\nKeep the core engaged.\nLower the body under control.\nPush back up."
  },
  {
    "id": "pushup:common-push-up-mistakes:1",
    "documentId": "pushup",
    "title": "Push-up Improvement",
    "section": "Common push-up mistakes",
    "content": "Common push-up mistakes include hips dropping, hips held too high, shallow movement, elbows forced too far outward, and rushing repetitions. Keep a controlled body position and choose a range of motion and variation you can maintain."
  },
  {
    "id": "pushup:hips-dropping:1",
    "documentId": "pushup",
    "title": "Push-up Improvement",
    "section": "Hips dropping",
    "content": "The body should remain controlled instead of letting the hips sag.\n\nCue:\n\"Keep your body in one line.\""
  },
  {
    "id": "pushup:hips-too-high:1",
    "documentId": "pushup",
    "title": "Push-up Improvement",
    "section": "Hips too high",
    "content": "The exercise becomes less like a standard push-up.\n\nCue:\n\"Keep your hips in line with your shoulders and legs.\""
  },
  {
    "id": "pushup:not-lowering-enough:1",
    "documentId": "pushup",
    "title": "Push-up Improvement",
    "section": "Not lowering enough",
    "content": "Use a controlled range of motion that the person can maintain."
  },
  {
    "id": "pushup:elbows-moving-too-far-outward:1",
    "documentId": "pushup",
    "title": "Push-up Improvement",
    "section": "Elbows moving too far outward",
    "content": "Keep the elbows controlled rather than forcing them directly sideways."
  },
  {
    "id": "pushup:moving-too-quickly:1",
    "documentId": "pushup",
    "title": "Push-up Improvement",
    "section": "Moving too quickly",
    "content": "Slow down and control both directions."
  },
  {
    "id": "pushup:incomplete-repetition:1",
    "documentId": "pushup",
    "title": "Push-up Improvement",
    "section": "Incomplete repetition",
    "content": "A repetition should meet the person's chosen range-of-motion standard."
  },
  {
    "id": "pushup:push-up-progression:1",
    "documentId": "pushup",
    "title": "Push-up Improvement",
    "section": "Push-up progression",
    "content": "Easier:\n\nWall push-up\nHigh incline push-up\nLower incline push-up\nKnee push-up when appropriate\n\nStandard:\n5. Regular push-up\n\nHarder:\n6. Close-grip push-up\n7. Decline push-up\n8. Other controlled variations"
  },
  {
    "id": "pushup:improving-push-up-strength:1",
    "documentId": "pushup",
    "title": "Push-up Improvement",
    "section": "Improving push-up strength",
    "content": "Progress by:\n\nIncreasing repetitions\nIncreasing range of motion\nUsing a harder variation\nImproving control\nReducing unnecessary rest when appropriate\n\nDo not increase difficulty so much that technique becomes poor."
  },
  {
    "id": "pushup:technique-cues:1",
    "documentId": "pushup",
    "title": "Push-up Improvement",
    "section": "Technique cues",
    "content": "Possible technique cues:\n\nHips dropping → \"Keep your body straight.\"\nHigh hips → \"Keep your hips aligned.\"\nShallow movement → \"Use a controlled range of motion.\"\nPoor control → \"Slow the movement down.\""
  },
  {
    "id": "recovery:why-recovery-matters:1",
    "documentId": "recovery",
    "title": "Recovery and Rest",
    "section": "Why recovery matters",
    "content": "The body adapts to training during recovery.\n\nRecovery supports:\n\nMuscle repair\nStrength improvement\nEnergy\nTraining performance\nConsistency"
  },
  {
    "id": "recovery:sleep:1",
    "documentId": "recovery",
    "title": "Recovery and Rest",
    "section": "Sleep",
    "content": "Good sleep is important for physical performance and recovery.\n\nMost adults should aim for roughly 7–9 hours of sleep, although individual needs can vary."
  },
  {
    "id": "recovery:rest-days:1",
    "documentId": "recovery",
    "title": "Recovery and Rest",
    "section": "Rest days",
    "content": "A person does not need to train hard every day.\n\nRest days can include:\n\nComplete rest\nWalking\nLight mobility\nEasy activity"
  },
  {
    "id": "recovery:muscle-soreness:1",
    "documentId": "recovery",
    "title": "Recovery and Rest",
    "section": "Muscle soreness",
    "content": "Mild muscle soreness can happen after unfamiliar or harder exercise.\n\nSoreness does not automatically mean a workout was better.\n\nA person should not use severe soreness as a target."
  },
  {
    "id": "recovery:hydration:1",
    "documentId": "recovery",
    "title": "Recovery and Rest",
    "section": "Hydration",
    "content": "Drink water regularly.\n\nFluid needs increase with:\n\nHeat\nSweating\nLong workouts\nRunning\nSports"
  },
  {
    "id": "recovery:food-and-recovery:1",
    "documentId": "recovery",
    "title": "Recovery and Rest",
    "section": "Food and recovery",
    "content": "Recovery requires enough energy and nutrients.\n\nUseful foods include:\n\nProtein-rich foods\nCarbohydrates\nFruits\nVegetables\nHealthy fats"
  },
  {
    "id": "recovery:training-fatigue:1",
    "documentId": "recovery",
    "title": "Recovery and Rest",
    "section": "Training fatigue",
    "content": "Signs that training may need adjustment:\n\nPerformance consistently getting worse\nConstant tiredness\nPoor sleep\nPersistent soreness\nLoss of motivation\nDifficulty completing normal workouts\n\nThe person may benefit from reducing training difficulty or taking additional recovery."
  },
  {
    "id": "recovery:warm-up:1",
    "documentId": "recovery",
    "title": "Recovery and Rest",
    "section": "Warm-up",
    "content": "A warm-up prepares the body for activity.\n\nA simple warm-up can include:\n\nLight walking\nEasy jogging\nDynamic movement\nMovement-specific practice"
  },
  {
    "id": "recovery:cool-down:1",
    "documentId": "recovery",
    "title": "Recovery and Rest",
    "section": "Cool-down",
    "content": "A cool-down can involve:\n\nEasy walking\nGentle movement\nGradually lowering exercise intensity\n\nA cool-down does not need to be complicated."
  },
  {
    "id": "running:running-goals:1",
    "documentId": "running",
    "title": "Running Improvement",
    "section": "Running goals",
    "content": "Running can improve:\n\nCardiovascular fitness\nStamina\nSpeed\nRunning efficiency\nOverall endurance\n\nA person does not need to run fast every session."
  },
  {
    "id": "running:beginner-running:1",
    "documentId": "running",
    "title": "Running Improvement",
    "section": "Beginner running",
    "content": "A beginner can start with a combination of walking and running.\n\nExample:\n\nWalk for a few minutes\nJog for a short period\nWalk again\nRepeat\n\nGradually increase running time as fitness improves."
  },
  {
    "id": "running:improving-running-endurance:1",
    "documentId": "running",
    "title": "Running Improvement",
    "section": "Improving running endurance",
    "content": "The main idea is gradual progression.\n\nIncrease only one major training demand at a time.\n\nPossible progression:\n\nMore running time\nSlightly longer distance\nBetter consistency\nSlightly faster pace\n\nDo not suddenly double running volume."
  },
  {
    "id": "running:easy-running:1",
    "documentId": "running",
    "title": "Running Improvement",
    "section": "Easy running",
    "content": "Most running should feel controlled enough that the person could maintain a conversation, depending on fitness level.\n\nEasy running helps build an aerobic base."
  },
  {
    "id": "running:speed-work:1",
    "documentId": "running",
    "title": "Running Improvement",
    "section": "Speed work",
    "content": "More advanced runners can use:\n\nIntervals\nTempo runs\nShort faster efforts\n\nSpeed work is more demanding and should not be performed hard every day."
  },
  {
    "id": "running:running-form:1",
    "documentId": "running",
    "title": "Running Improvement",
    "section": "Running form",
    "content": "Useful general principles:\n\nMaintain relaxed shoulders\nAvoid unnecessary tension\nKeep arms controlled\nMaintain a comfortable posture\nAvoid forcing an unnatural stride\n\nThere is no single perfect running style for every person."
  },
  {
    "id": "running:running-stamina:1",
    "documentId": "running",
    "title": "Running Improvement",
    "section": "Running stamina",
    "content": "Stamina improves through consistent aerobic training.\n\nUseful activities:\n\nWalking\nJogging\nRunning\nCycling\nSwimming\nSports"
  },
  {
    "id": "running:running-and-strength-training:1",
    "documentId": "running",
    "title": "Running Improvement",
    "section": "Running and strength training",
    "content": "Strength training can support running by improving muscular strength and control.\n\nUseful exercises:\n\nSquats\nSplit squats\nLunges\nCalf raises\nHip hinges\nCore exercises\n\nAvoid doing every workout at maximum intensity."
  },
  {
    "id": "running:recovery:1",
    "documentId": "running",
    "title": "Running Improvement",
    "section": "Recovery",
    "content": "If a person develops unusual or persistent pain, they should stop and seek appropriate professional advice rather than trying to run through it."
  },
  {
    "id": "squat:main-goal:1",
    "documentId": "squat",
    "title": "Squat Improvement",
    "section": "Main goal",
    "content": "The squat trains the legs and hips and also requires core and body control."
  },
  {
    "id": "squat:good-squat-form-and-setup:1",
    "documentId": "squat",
    "title": "Squat Improvement",
    "section": "Good squat form and setup",
    "content": "Stand with feet in a comfortable position.\nKeep the feet stable.\nKeep the body balanced.\nBegin the movement by bending the hips and knees.\nLower under control.\nStand back up smoothly."
  },
  {
    "id": "squat:squat-depth-and-comfortable-range-of-motion:1",
    "documentId": "squat",
    "title": "Squat Improvement",
    "section": "Squat depth and comfortable range of motion",
    "content": "Depth depends on the person's mobility, body structure, experience, and goal.\n\nA person should use a range of motion they can control safely.\n\nOne exact knee angle is not perfect for every person."
  },
  {
    "id": "squat:common-squat-problems:1",
    "documentId": "squat",
    "title": "Squat Improvement",
    "section": "Common squat problems",
    "content": "Common squat problems include moving too quickly, using a depth you cannot control, excessive forward lean, knees moving inward, and heels lifting. Slow the movement down, keep your feet stable, and work within a comfortable range of motion."
  },
  {
    "id": "squat:insufficient-depth:1",
    "documentId": "squat",
    "title": "Squat Improvement",
    "section": "Insufficient depth",
    "content": "Possible causes:\n\nLack of confidence\nLimited mobility\nWeakness\n\nMoving too quickly\n\nUseful cue:\n\"Lower your hips with control.\""
  },
  {
    "id": "squat:excessive-forward-lean:1",
    "documentId": "squat",
    "title": "Squat Improvement",
    "section": "Excessive forward lean",
    "content": "Useful cue:\n\"Keep your chest more upright.\"\n\nThe person should not force an unnatural upright position."
  },
  {
    "id": "squat:knees-moving-inward:1",
    "documentId": "squat",
    "title": "Squat Improvement",
    "section": "Knees moving inward",
    "content": "The person should focus on controlled knee tracking and stable feet."
  },
  {
    "id": "squat:heels-lifting:1",
    "documentId": "squat",
    "title": "Squat Improvement",
    "section": "Heels lifting",
    "content": "Possible causes include:\n\nFoot position\nMobility limitations\nBalance problems\n\nThe person should work on controlled movement rather than forcing depth."
  },
  {
    "id": "squat:moving-too-quickly:1",
    "documentId": "squat",
    "title": "Squat Improvement",
    "section": "Moving too quickly",
    "content": "Slow down enough to control the descent and ascent."
  },
  {
    "id": "squat:improving-squat-strength:1",
    "documentId": "squat",
    "title": "Squat Improvement",
    "section": "Improving squat strength",
    "content": "Useful progressions:\n\nBodyweight squat\nPause squat\nTempo squat\nSplit squat\nReverse lunge\nBulgarian split squat\nLoaded squat when appropriate"
  },
  {
    "id": "squat:squat-practice:1",
    "documentId": "squat",
    "title": "Squat Improvement",
    "section": "Squat practice",
    "content": "A beginner can practice:\n\nConsistent stance\nControlled descent\nControlled ascent\nStable feet\nComfortable depth\n\nQuality is more important than rapidly increasing repetitions."
  },
  {
    "id": "squat:technique-cues:1",
    "documentId": "squat",
    "title": "Squat Improvement",
    "section": "Technique cues",
    "content": "Possible technique cues:\n\nShallow depth → encourage controlled deeper movement if appropriate\nForward lean → encourage better torso control\nKnee collapse → encourage controlled knee tracking\nIncomplete repetition → explain that the movement was not fully completed\n\nFeedback should be short and easy to understand."
  },
  {
    "id": "stamina:what-stamina-means:1",
    "documentId": "stamina",
    "title": "Stamina and Endurance",
    "section": "What stamina means",
    "content": "Stamina is the ability to continue an activity without becoming excessively tired.\n\nIt can refer to:\n\nRunning endurance\nSports endurance\nWorkout endurance\nGeneral physical endurance"
  },
  {
    "id": "stamina:how-stamina-improves:1",
    "documentId": "stamina",
    "title": "Stamina and Endurance",
    "section": "How stamina improves",
    "content": "Stamina improves through consistent training and gradual progression.\n\nUseful activities:\n\nWalking\nJogging\nRunning\nCycling\nSwimming\nSports\n\nCircuit training"
  },
  {
    "id": "stamina:aerobic-training:1",
    "documentId": "stamina",
    "title": "Stamina and Endurance",
    "section": "Aerobic training",
    "content": "Aerobic training improves the body's ability to use oxygen during sustained activity.\n\nExamples:\n\nBrisk walking\nEasy running\nCycling\nSwimming"
  },
  {
    "id": "stamina:interval-training:1",
    "documentId": "stamina",
    "title": "Stamina and Endurance",
    "section": "Interval training",
    "content": "Intervals alternate harder and easier periods.\n\nExample:\n\nEasy movement\n↓\nShort harder effort\n↓\nEasy recovery\n↓\nRepeat\n\nBeginners should start with manageable intervals."
  },
  {
    "id": "stamina:stamina-during-strength-workouts:1",
    "documentId": "stamina",
    "title": "Stamina and Endurance",
    "section": "Stamina during strength workouts",
    "content": "If someone gets tired quickly during strength training:\n\nRest enough between hard sets\nAvoid rushing repetitions\nImprove general cardio fitness\nStay hydrated\nEat enough\nSleep adequately\nGradually increase training volume"
  },
  {
    "id": "stamina:circuit-training:1",
    "documentId": "stamina",
    "title": "Stamina and Endurance",
    "section": "Circuit training",
    "content": "A circuit can combine several exercises with controlled rest.\n\nExample:\n\nSquat\n↓\nPush-up\n↓\nWalking/lunges\n↓\nCore exercise\n↓\nRest\n↓\nRepeat\n\nThe goal should be good movement, not simply doing everything as fast as possible."
  },
  {
    "id": "stamina:improving-work-capacity:1",
    "documentId": "stamina",
    "title": "Stamina and Endurance",
    "section": "Improving work capacity",
    "content": "Gradually increase:\n\nExercise duration\nNumber of rounds\nRepetition quality\nTraining consistency\n\nDo not increase all of them at the same time."
  },
  {
    "id": "stamina:fatigue:1",
    "documentId": "stamina",
    "title": "Stamina and Endurance",
    "section": "Fatigue",
    "content": "Normal exercise fatigue is different from severe symptoms.\n\nStop exercise if the person experiences concerning symptoms such as:\n\nChest pain\nFainting\nSevere dizziness\nSevere breathing difficulty\nSudden severe pain\n\nPersistent or concerning symptoms should be discussed with an appropriate healthcare professional."
  },
  {
    "id": "strength:what-strength-means:1",
    "documentId": "strength",
    "title": "Strength Gain",
    "section": "What strength means",
    "content": "Strength is the ability to produce force.\n\nGetting stronger means becoming able to:\n\nLift more weight\nPerform harder bodyweight exercises\nPerform more controlled repetitions\nMaintain better control during movement\n\nStrength and muscle size are related but are not exactly the same."
  },
  {
    "id": "strength:how-to-become-stronger:1",
    "documentId": "strength",
    "title": "Strength Gain",
    "section": "How to become stronger",
    "content": "The main principle is progressive overload.\n\nProgressive overload means gradually asking the body to do more over time.\n\nProgress can come from:\n\nMore weight\nMore repetitions\nMore difficult exercise variations\nBetter range of motion\nBetter control\nMore challenging positions\n\nProgress should be gradual.\n\nTrying to increase everything at once is unnecessary."
  },
  {
    "id": "strength:strength-training-repetitions:1",
    "documentId": "strength",
    "title": "Strength Gain",
    "section": "Strength training repetitions",
    "content": "Lower repetition ranges with challenging resistance are commonly useful for strength.\n\nHowever, beginners can become stronger across a wide range of repetitions.\n\nTechnique should be more important than chasing a number."
  },
  {
    "id": "strength:rest-between-hard-sets:1",
    "documentId": "strength",
    "title": "Strength Gain",
    "section": "Rest between hard sets",
    "content": "Strength work usually benefits from longer rest periods than light cardio.\n\nA person should rest enough to perform the next set with good technique.\n\nIf the next set becomes much worse because the person is still exhausted, more rest may be useful."
  },
  {
    "id": "strength:strength-exercises:1",
    "documentId": "strength",
    "title": "Strength Gain",
    "section": "Strength exercises",
    "content": "Useful movements include:\n\nLower body:\n\nSquats\nSplit squats\nLunges\nDeadlift variations\nHip thrusts\n\nUpper body:\n\nPush-ups\nBench press\nOverhead press\nRows\nPull-ups\n\nCore:\n\nPlanks\nSide planks\nDead bugs\nLoaded carries when equipment is available"
  },
  {
    "id": "strength:beginner-strength-training:1",
    "documentId": "strength",
    "title": "Strength Gain",
    "section": "Beginner strength training",
    "content": "Beginners should focus on:\n\nLearning the movement\nUsing manageable difficulty\nMaintaining good form\nTraining consistently\nGradually increasing difficulty\n\nA beginner does not need to train to complete exhaustion."
  },
  {
    "id": "strength:strength-without-equipment:1",
    "documentId": "strength",
    "title": "Strength Gain",
    "section": "Strength without equipment",
    "content": "Bodyweight progression can be used.\n\nFor push-ups:\n\nWall push-up\nIncline push-up\nKnee push-up\nStandard push-up\nClose-grip push-up\nDecline push-up\nOther harder variations\n\nFor legs:\n\nSquat\nPause squat\nSplit squat\nReverse lunge\nBulgarian split squat\nSingle-leg variations"
  },
  {
    "id": "strength:strength-plateaus:1",
    "documentId": "strength",
    "title": "Strength Gain",
    "section": "Strength plateaus",
    "content": "If progress stops:\n\nCheck technique\nCheck recovery\nCheck sleep\nCheck whether training is consistent\nAvoid increasing difficulty too quickly\nChange the exercise variation if needed\nAllow enough recovery\n\nA plateau does not always mean the person needs more training."
  },
  {
    "id": "user_manual:getting-started-and-choosing-a-goal:1",
    "documentId": "user_manual",
    "title": "Using VYRA",
    "section": "Getting started and choosing a goal",
    "content": "Create or restore your guest profile, then choose a fitness goal: build mass, reduce weight, or build strength while maintaining weight. Enter current height and weight, a target weight, and the starting build that best describes you. Starting build is self-described; the app does not diagnose you from body size.\n\nChoose from Goku, Base Male, Base Female, Mikasa, Nami, and Sakura. A new player starts at Starter. Changing characters keeps your earned progress, goal, reports, and cosmetic ownership."
  },
  {
    "id": "user_manual:character-evolution:1",
    "documentId": "user_manual",
    "title": "Using VYRA",
    "section": "Character evolution",
    "content": "Your character advances through Starter, Developing, Strong, and Elite. Evolution combines qualifying workouts, XP, distinct active days, and later check-ins toward your chosen target weight. Elite is the final earned stage. Reaching a weight target alone does not complete the workout requirements.\n\nDeveloping requires 100 XP, 1 active day, and 25% target progress. Strong requires 1,000 XP, 5 active days, and 60%. Elite requires 3,000 XP, 14 active days, and 100%. For maintenance, a later report within 2% of target weight satisfies the weight part. Earned stages do not fall back because of normal fluctuations."
  },
  {
    "id": "user_manual:body-check-ins:1",
    "documentId": "user_manual",
    "title": "Using VYRA",
    "section": "Body check-ins",
    "content": "After setup, report current weight and height in your profile. Your first follow-up is available from the next day in Asia/Kolkata time. Updating the same day replaces that day's report. Weekly check-ins can help show trends; you do not need to enter measurements every day. Your starting baseline stays fixed.\n\nWeight cannot measure muscle or fitness on its own. The reports support the goal you chose and should not encourage rapid weight changes."
  },
  {
    "id": "user_manual:arena-opponent-search-and-private-battles:1",
    "documentId": "user_manual",
    "title": "Using VYRA",
    "section": "Arena opponent search and private battles",
    "content": "In Arena, create a private 1v1 room, join a room with a code, or search for a random opponent. Opponent search happens before camera preparation. Once both players are in the lobby, use Prepare my camera, allow camera access, get into position, and complete calibration before marking yourself ready.\n\nYour friend may still be preparing their camera while you wait in the lobby. The normal workout flow uses real camera rep tracking, not simulated repetitions."
  },
  {
    "id": "user_manual:solo-workouts-and-camera-setup:1",
    "documentId": "user_manual",
    "title": "Using VYRA",
    "section": "Solo workouts and camera setup",
    "content": "Solo training prepares the camera before the workout. Use a supported browser or app, allow camera permission, give yourself enough room, and keep the required body joints visible in good lighting. Position the camera so the exercise can be seen clearly. Recalibrate if your position changes.\n\nIf tracking cannot see you clearly, improve the camera position or lighting before continuing. Leaving an active workout or moving the app into the background can end tracking; do not rely on an automatic pause-and-resume feature."
  },
  {
    "id": "user_manual:repetition-counting-and-technique-feedback:1",
    "documentId": "user_manual",
    "title": "Using VYRA",
    "section": "Repetition counting and technique feedback",
    "content": "VYRA uses movement landmarks and calibration for supported camera exercises. Complete controlled repetitions and keep the relevant body joints visible. Tracking can miss a repetition when visibility or movement is incomplete. Camera feedback is a training aid, not a medical assessment or a guarantee of perfect technique.\n\nStop if an exercise causes sharp, severe, or unusual pain. Adjust the difficulty instead of forcing repetitions to satisfy the counter."
  },
  {
    "id": "user_manual:workout-rewards:1",
    "documentId": "user_manual",
    "title": "Using VYRA",
    "section": "Workout rewards",
    "content": "Finish a workout with at least 10 valid repetitions to qualify. The first three qualifying workouts per day earn XP and help build your active-day progress. Extra valid workouts can still contribute repetitions and battle wins to cosmetic unlocks. Previewing a character or cosmetic never earns rewards."
  },
  {
    "id": "user_manual:collection-previews-and-character-selection:1",
    "documentId": "user_manual",
    "title": "Using VYRA",
    "section": "Collection previews and character selection",
    "content": "Collection lets you preview all six characters and their four progression stages. A preview does not change your saved stage. Select a character to save it to your profile. Earned cosmetic effects can be equipped on every character; locked effects can be previewed before unlocking."
  },
  {
    "id": "user_manual:cosmetic-unlocks-equip-remove-and-original-look:1",
    "documentId": "user_manual",
    "title": "Using VYRA",
    "section": "Cosmetic unlocks, equip, remove, and original look",
    "content": "- Ion skin unlocks after your first qualifying workout.\n- Pulse bracers unlock after 100 valid repetitions.\n- Champion flex unlocks after 5 battle wins.\n- Nova aura unlocks at Elite.\n\nEquip an owned effect, remove it from its slot, or restore the character's original look to clear all equipped effects. Ownership, character selection, stage, XP, and fitness reports remain saved. Cosmetics change appearance and animation; they do not improve battle scoring or physical fitness."
  },
  {
    "id": "user_manual:coach-questions-and-sources:1",
    "documentId": "user_manual",
    "title": "Using VYRA",
    "section": "Coach questions and sources",
    "content": "Ask Coach about exercise technique, strength, muscle gain, running, stamina, recovery, everyday food choices, or how VYRA works. Coach retrieves relevant passages from this bundled guide and shows the sources. When an AI provider is enabled, it can phrase an answer from those passages; otherwise you receive guide excerpts directly.\n\nYour question and the recent conversation you submit may be sent to the configured AI provider. Profile measurements are not attached automatically. Source passages are general information and may not answer individual medical or nutrition questions."
  }
];
