// Generated by scripts/character-assets.mjs. GLBs remain lazy: only the selected file is decoded.
import type { CharacterId, EvolutionStage } from '@vyra/core';
import { characterFor } from '@vyra/core';

export const CHARACTER_ASSETS = {
  'goku': {
    starter: require('../../assets/characters/goku/starter.glb'),
    developing: require('../../assets/characters/goku/developing.glb'),
    strong: require('../../assets/characters/goku/strong.glb'),
    elite: require('../../assets/characters/goku/elite.glb'),
    legendary: require('../../assets/characters/goku/legendary.glb'),
  },
  'base-male': {
    starter: require('../../assets/characters/base-male/starter.glb'),
    developing: require('../../assets/characters/base-male/developing.glb'),
    strong: require('../../assets/characters/base-male/strong.glb'),
    elite: require('../../assets/characters/base-male/elite.glb'),
    legendary: require('../../assets/characters/base-male/legendary.glb'),
  },
  'base-female': {
    starter: require('../../assets/characters/base-female/starter.glb'),
    developing: require('../../assets/characters/base-female/developing.glb'),
    strong: require('../../assets/characters/base-female/strong.glb'),
    elite: require('../../assets/characters/base-female/elite.glb'),
    legendary: require('../../assets/characters/base-female/legendary.glb'),
  },
  'mikasa': {
    starter: require('../../assets/characters/mikasa/starter.glb'),
    developing: require('../../assets/characters/mikasa/developing.glb'),
    strong: require('../../assets/characters/mikasa/strong.glb'),
    elite: require('../../assets/characters/mikasa/elite.glb'),
    legendary: require('../../assets/characters/mikasa/legendary.glb'),
  },
  'nami': {
    starter: require('../../assets/characters/nami/starter.glb'),
    developing: require('../../assets/characters/nami/developing.glb'),
    strong: require('../../assets/characters/nami/strong.glb'),
    elite: require('../../assets/characters/nami/elite.glb'),
    legendary: require('../../assets/characters/nami/legendary.glb'),
  },
  'sakura': {
    starter: require('../../assets/characters/sakura/starter.glb'),
    developing: require('../../assets/characters/sakura/developing.glb'),
    strong: require('../../assets/characters/sakura/strong.glb'),
    elite: require('../../assets/characters/sakura/elite.glb'),
    legendary: require('../../assets/characters/sakura/legendary.glb'),
  },
} satisfies Record<CharacterId, Record<EvolutionStage, number>>;

export const CHARACTER_ART = {
  'goku': require('../../assets/characters/goku/card.png'),
  'base-male': require('../../assets/characters/base-male/card.png'),
  'base-female': require('../../assets/characters/base-female/card.png'),
  'mikasa': require('../../assets/characters/mikasa/card.png'),
  'nami': require('../../assets/characters/nami/card.png'),
  'sakura': require('../../assets/characters/sakura/card.png'),
} satisfies Record<CharacterId, number>;

export const CHARACTER_PRESENTATIONS = {
  "goku": {
    "scale": 1.8005494721,
    "position": [
      0.0018545088099,
      0.90000000348,
      -0.011272868453
    ],
    "yaw": -1.37,
    "galleryYaw": -2.71,
    "accent": "#3D7BFF",
    "framing": {
      "fitHeight": 2.12,
      "fitWidth": 1.5275674304,
      "centerY": 0.94
    }
  },
  "base-male": {
    "scale": 0.005979073207,
    "position": [
      0.0040842295636,
      -0.55072073298,
      -0.016385331944
    ],
    "yaw": 0,
    "galleryYaw": -0.22,
    "accent": "#8B5CF6",
    "framing": {
      "fitHeight": 2.12,
      "fitWidth": 3.9975813723,
      "centerY": 0.94
    }
  },
  "base-female": {
    "scale": 0.40563990404,
    "position": [
      0,
      -0.0081234730564,
      0.022286429955
    ],
    "yaw": 0,
    "galleryYaw": -0.22,
    "accent": "#2DD4BF",
    "framing": {
      "fitHeight": 2.12,
      "fitWidth": 1.4761033124,
      "centerY": 0.94
    }
  },
  "mikasa": {
    "scale": 0.50351262144,
    "position": [
      -3.7223024882e-7,
      -3.2448723344e-7,
      -0.023875037381
    ],
    "yaw": 0,
    "galleryYaw": -0.22,
    "accent": "#FF5A5F",
    "framing": {
      "fitHeight": 2.12,
      "fitWidth": 1.3840854942,
      "centerY": 0.94
    }
  },
  "nami": {
    "scale": 0.85747976615,
    "position": [
      -3.6483129665e-8,
      5.8128029425e-7,
      -2.5956185059e-8
    ],
    "yaw": 0,
    "galleryYaw": -0.22,
    "accent": "#FF6B3D",
    "framing": {
      "fitHeight": 2.12,
      "fitWidth": 1.8841349305,
      "centerY": 0.94
    }
  },
  "sakura": {
    "scale": 0.011064367878,
    "position": [
      -0.000074115867588,
      0.0040185564184,
      0.0085832379128
    ],
    "yaw": 0,
    "galleryYaw": -0.22,
    "accent": "#4ADE80",
    "framing": {
      "fitHeight": 2.12,
      "fitWidth": 1.5718346211,
      "centerY": 0.94
    }
  }
} as const;

export function characterAssetFor(characterId: unknown, stage: EvolutionStage) {
  const id = characterFor(characterId).id;
  return CHARACTER_ASSETS[id][stage] ?? CHARACTER_ASSETS[id].starter;
}

export const characterTitleFor = (characterId: unknown) => characterFor(characterId).name;
